import os
import logging
from datetime import datetime

logger = logging.getLogger(__name__)


def _section(title: str, findings: dict, formatter) -> str:
    """Build a single report section"""
    lines = [f"## {title}\n"]
    if not findings:
        lines.append("No threats detected.\n")
    else:
        for key, value in findings.items():
            lines.append(formatter(key, value))
    lines.append("")
    return "\n".join(lines)


def build_report(log_file: str, entries: list, findings: dict) -> str:
    """Build a structured Markdown report from analysis findings"""
    now = datetime.now()
    total = len(entries)
    threat_ips = set()
    for v in findings.values():
        threat_ips.update(v.keys())

    report = f"""# Security Log Analysis Report
**File:** `{log_file}`
**Generated:** {now.strftime("%Y-%m-%d %H:%M:%S")}
**Entries analysed:** {total}
**Suspicious IPs identified:** {len(threat_ips)}

---

"""

    report += _section(
        "🔍 404 Scanning",
        findings["404_scanning"],
        lambda ip, count: f"- `{ip}` — {count} x 404 errors\n"
    )

    report += _section(
        "🔥 High Request Volume",
        findings["high_volume"],
        lambda ip, count: f"- `{ip}` — {count} requests\n"
    )

    report += _section(
        "🛠️ Suspicious User Agents",
        findings["suspicious_agents"],
        lambda ip, agents: f"- `{ip}` — {', '.join(agents)}\n"
    )

    report += _section(
        "📁 Directory Traversal Attempts",
        findings["traversal"],
        lambda ip, count: f"- `{ip}` — {count} attempt(s)\n"
    )

    report += _section(
        "💉 SQL Injection Attempts",
        findings["sqli"],
        lambda ip, count: f"- `{ip}` — {count} attempt(s)\n"
    )

    report += "---\n*Report generated by security-toolkit — LeightonSec*\n"
    return report


def save_report(report: str, log_file: str) -> str:
    """Save report to reports/ directory — returns the saved file path"""
    os.makedirs("reports", exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    base = os.path.splitext(os.path.basename(log_file))[0]
    filename = f"report_{base}_{timestamp}.md"
    path = os.path.join("reports", filename)
    with open(path, "w", encoding="utf-8") as f:
        f.write(report)
    logger.info(f"Report saved: {path}")
    return path
